---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/alexanderlowe/Library/Developer/Xcode/DerivedData/SettingsUI_Internal-evnqypmroatgovcjgxosvfdvnejp/Build/Intermediates.noindex/ArchiveIntermediates/SettingsUI_Internal/InstallationBuildProductsLocation/Library/Frameworks/SettingsUI_Internal.framework/SettingsUI_Internal'
relocations:     []
...
